name = "BBI"
uuid = "19670fab-07f0-5a41-99c5-c090d774ee27"
authors = ["Ciarán O’Mara <CiaranOMara@utas.edu.au>"]
version = "0.2.0"

[deps]
BioCore = "37cfa864-2cd6-5c12-ad9e-b6597d696c81"
Libz = "2ec943e9-cfe8-584d-b93d-64dcb6d567b7"

[compat]
BioCore = "2"
Libz = "1"
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
